# Generated by Django 3.1.4 on 2021-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=90)),
                ('quantity', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('C', 'CARBOHYDRATES'), ('F', 'FRUITS'), ('D', 'DRINKS'), ('FO', 'FOOD'), ('N', 'NO_CATEGORY')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
